stream
lesiw/bump pull request #3
Opened 2023-10-13 07:02 UTC by booniepepper

- Add aqua and ignore executable if built in project dir
- Stream over stdin

2023-10-13 09:15 UTC, lesiw requested changes

2023-10-13 09:15 UTC, lesiw commented on bump.go
> +		}
I don't want to extend `main()` to add this; `main()`'s only job is to check if `run()` errored and to set the return code appropriately / write to standard error.

It's better to extend `run()` and return an error if something failed.

2023-10-13 09:15 UTC, lesiw commented on bump.go
> +func readInput(reader *bufio.Reader) (string, error) {
I think the right thing to do here would be to change this function to emit `<-chan string` and loop over the channel in `run()`.

2023-10-13 09:41 UTC, lesiw commented
Since we'll be streaming, it's worth thinking about changing how errors will be handled. Right now, we fail and quit the program on unrecognizable input, so `1.2.3\nfoo\n1.0.0\n` would stop after hitting `foo`. I don't think that's the right behavior.

We could probably borrow from `grep` here and no longer consider a failure to match a reason to stop streaming. Instead, parse errors should be written to stderr as they're encountered, but not stop the program.

Also, like `grep`, we might not want to use the return code as an indicator that an error happened, but instead as an indicator whether a successful parse occurred: `0` if at least one parseable version was found in the stream, `1` if not, `2` or greater for a non-streaming error (like flag validation, if we had it; compare to passing `grep` an invalid regex).

2023-10-13 10:22 UTC, booniepepper commented
A little rushed but it does the thing

```
❯ echo -e '1\nfoo\n7' | ./bump
2
error bumping version: no version segments found in 'foo'
8

❯ echo -e '1\nfoo\n7' | ./bump 2>/dev/null
2
8

❯ echo -e '1\nfoo\n7' | ./bump >/dev/null
error bumping version: no version segments found in 'foo'
```

Let's think it over a bit tho. Needs tests too

2023-10-13 10:23 UTC, booniepepper commented on bump.go
> +			lines <- ReadLine{strings.TrimSpace(input), err}
go fmt

2023-10-13 10:23 UTC, booniepepper commented on bump.go
> +var segstr *string
move

2023-10-13 10:24 UTC, booniepepper commented on bump.go
> +			return read.Error
Note to self: Should a failed read be an `os.Exit(...)` case?

2023-11-29 00:10 UTC, booniepepper commented
YAGNI?

2023-11-29 02:08 UTC, merged